// English alt texts of content/prints.mjs (same ids).

export const PRINT_ALT_EN = {
  'biblioteca': 'Library in touch mode, landscape: rail with the app\'s areas on the left, search, filters, cover grid and, on the right, the selected game\'s panel with Play and the quick settings.',
  'biblioteca-retrato': 'Library in touch mode, portrait: cover grid with the area bar at the bottom.',
  'biblioteca-controle': 'Library in controller mode: carousel of large covers, tabs at the top switched with LB and RB, the cover\'s color in the background and the button hints at the bottom.',
  'ficha': 'Game details: sections on the left (overview, settings groups, performance, patches and content, saves and data) and, at the top, Start with… and Play.',
  'ficha-desempenho': 'Performance section of the details: the selected session, charts of FPS per second and of frame time, and the run\'s timeline.',
  'ficha-patches': 'Patches in the details, in groups: for your version of the game, for other versions and with no version stated.',
  'iniciar-com': 'Start with… sheet: profile, driver, executable, without patches, ignore the game\'s settings and extra command line, for this launch only.',
  'menu-imagem': 'In-game menu in the Image category: rail with Image, Performance, HUD, Controls and Session, and the screen and effects options with each row\'s value.',
  'menu-sessao': 'In-game menu in the Session category: sound, settings kept for the game with Undo, pause when the menu opens, continue and exit the game.',
  'hud': 'Performance HUD as a bar at the top of the screen, with FPS, frame time and color-coded metrics.',
  'configuracoes': 'Settings in the Interface section: interface mode (Automatic, Touch, Controller), settings shown (Essential, Advanced and All, with how many settings each level shows), buttons in the menus and suggestions after a session.',
  'configuracoes-imagem': 'Settings in the Image group: each setting with its value, its source (default or changed) and whether it changes live or at the next launch.',
  'configuracoes-busca': 'Search within a Settings tab, with results from other tabs below.',
  'drivers': 'GPU drivers: the chosen driver and the one the last session loaded, installed packages, packages to download, sources and Turnip options.',
  'drivers-baixar': 'Drivers to download: packages from the GitHub sources with size, date and the published SHA-256 badge.',
  'controles': 'Controls area: who plays as P1 to P4, touch options, physical controllers, vibration and motion, phones and the tools.',
  'controles-moderno': 'Touch controls in the Modern look over the game: dark glass buttons with colored A, B, X and Y letters.',
  'editor-toque': 'Touch editor: the controls over a grid and the panel of the selected control, with size, dead zone and show or hide.',
  'jogos-que-sairam': 'Games no longer in the library: saved cover, reason, time played, Title ID and the previous path.',
  'mapeamento': 'Key mapping: a drawn controller and the list of the 16 buttons with each one\'s key.',
  'testar-controles': 'Test controllers: the drawn controller lights up what is pressed, with sticks, triggers and dead zone.',
  'celular-controle': 'Phone as controller: game address, 6-digit code, name shown and Connect.',
  'perfis': 'Profiles: cards with avatar, gamertag, language, region and the active profile as P1.',
  'saves': 'A game\'s saves by profile, with export, import and the synchronization folder.',
  'conteudo': 'Content area: installed DLC and title updates by game, with sizes.',
  'instalar-conteudo': 'Install content: packages found in Downloads and in the content folders, with the game and type of each one.',
  'diagnostico': 'Diagnostics: saved sessions, how each one ended and the selected session\'s summary.',
  'diagnostico-resumo': 'Before sharing a session: what goes in the file and what is left out (paths, gamertags, addresses and tokens).',
  'comparar': 'Compare runs: runs marked A or B, the result per pair and the warnings.',
  'sugestoes': 'Suggestions sheet after a session, with the reason in numbers and Apply to this game.',
  'primeira-abertura': 'First-run assistant, This phone step: checks for a Vulkan GPU, 64-bit ARM, Android and a games folder.',
  'primeira-abertura-jogos': 'First-run assistant, Your games step: the chosen folder, the scan and the covers found.',
  'pastas': 'Game folders with Create standard folders: XenDroid/Games, TU and DLC.',
  'navegador': 'Folder browser: internal storage and SD card, the path as steps and how many games each folder has.',
  'sem-vulkan': '“This device has no Vulkan GPU” screen, with the checks and Copy the device data.',
  'atualizador': 'App updates: installed version, channel, last check and the update card with the steps download, check the SHA-256 and install.',
  'sobre': 'About: version, the device in a table with Copy all, shortcuts and credits.',
  'carregamento': 'Game loading with the launch steps, the time each one took and what applies to this launch.',
  'falha-ao-abrir': 'Launch failure: the reason in one sentence, the last lines of the log and the next step.',
  'mensagem': 'Game message panel, with the title, the text and the options as full-width rows.',
  'teclado': 'Game keyboard: the request, the field with the character limit and the key grid.',
  'troca-de-disco': 'Disc swap: the requested disc highlighted and the discs found.',
};
