// Textos do simulador escritos à mão: o que cada tela é no app, como chegar nela, os arquivos
// do código e os prints reais. O build confere se cada arquivo e cada print existem.
// Caminhos de código são relativos a app/src/main/java/xendroid/compose/.

export const SIM_GROUPS = [
  ['Biblioteca e jogo', ['library', 'game']],
  ['Configurações e drivers', ['settings', 'drivers']],
  ['Jogo aberto', ['loading', 'launchfail', 'ingame', 'hud']],
  ['Controles', ['controls', 'keymap', 'touchedit', 'padtest', 'phonepad']],
  ['Perfis e saves', ['profiles', 'saves']],
  ['Conteúdo e diagnóstico', ['content', 'diagnostics', 'compare']],
  ['Primeira abertura e app', ['firstrun', 'folders', 'browse', 'missing', 'novulkan', 'update', 'about']],
  ['Painéis do jogo', ['msgbox', 'keyboard', 'discswap']],
];

/** Os jogos do README que formam a biblioteca de exemplo: nome na tabela → Title ID. */
export const README_TITLES = {
  'Forza Horizon': '4D5309C9',
  'Forza Horizon 2': '4D530AA4',
  'Gears of War 3': '4D5308AB',
  'Halo 4': '4D530919',
  'Need for Speed: Most Wanted': '45410961',
  'Sonic Unleashed': '53450812',
  'Halo: Reach': '4D53085B',
  'Crysis 3': '4541098E',
  'Grand Theft Auto IV': '545407F2',
  'Red Dead Redemption': '5454082B',
};

export const SIM_SCREENS = {
  library: {
    what: 'A biblioteca dos seus jogos. No toque, grade de capas em três tamanhos, busca por nome ou Title ID, ordem, filtros sempre à vista e, deitado, o painel do jogo escolhido com Jogar e os ajustes rápidos. No modo controle, um carrossel de capas com abas trocadas por LB e RB e a cor tirada da capa.',
    where: 'É a tela inicial do app; no trilho, Jogos.',
    c: 'Carrossel de capas, abas por LB/RB, Y favorita, X abre a ficha, Start (≡) abre o menu do app.',
    code: ['ui/library/GameLibraryScreen.kt', 'ui/library/LibraryTouch.kt', 'ui/library/LibraryModel.kt'],
    prints: ['biblioteca', 'biblioteca-retrato', 'biblioteca-controle'],
  },
  game: {
    what: 'A ficha de um jogo: Jogar e Iniciar com… sempre à vista, a visão geral, os ajustes deste jogo por grupo (com a troca para os globais), o desempenho das sessões, patches e conteúdo, saves e dados. O botão TOML mostra o arquivo de configuração do jogo no formato que o núcleo lê.',
    where: 'Biblioteca → toque num jogo (deitado, Ficha no painel ao lado; ou toque longo).',
    c: 'Menu vertical (Jogar, Iniciar com…, Ajustes rápidos, Todos os ajustes, Desempenho, Patches e conteúdo, Saves e dados, Compatibilidade); ◀ ▶ muda valores.',
    code: ['ui/game/GameScreen.kt', 'ui/game/GameCards.kt', 'ui/game/LaunchSheet.kt', 'ui/settings/XdSettings.kt'],
    prints: ['ficha', 'ficha-desempenho', 'ficha-patches', 'iniciar-com'],
  },
  settings: {
    what: 'Os ajustes que valem para todos os jogos: um resumo do que está fora do padrão e dos jogos com ajustes próprios, os oito grupos de ajustes do emulador e as opções do próprio app (interface, idioma, dados e backup, atualizações, comunidade, diagnóstico).',
    where: 'Trilho → Ajustes (embaixo); com controle, menu Start → Configurações.',
    c: 'Menu vertical com os mesmos grupos; ajustes em linhas ◀ ▶, LB/RB troca de grupo.',
    code: ['ui/settings/SettingsScreen.kt', 'ui/settings/XdSettings.kt', 'ui/settings/SettingRows.kt', 'ui/settings/AppRows.kt'],
    prints: ['configuracoes', 'configuracoes-imagem', 'configuracoes-busca'],
  },
  drivers: {
    what: 'O gerenciador de drivers da GPU: o driver escolhido e o que a última sessão carregou, a sugestão para a GPU, os instalados com o resultado da conferência do SHA-256, os disponíveis nas fontes, as fontes e as flags do Turnip.',
    where: 'Trilho → Drivers (deitado); menu Start com controle; em pé, Configurações → Resumo → Driver → Gerenciar drivers.',
    c: 'Mesmas seções no menu vertical; A usa ou baixa o driver em foco.',
    code: ['ui/drivers/DriversScreen.kt', 'driver/DriverSources.kt', 'driver/DriverSuggestion.kt', 'settings/TurnipFlags.kt'],
    prints: ['drivers', 'drivers-baixar'],
  },
  loading: {
    what: 'O carregamento de um jogo: as etapas da abertura com o tempo de cada uma, a contagem de pipelines criados e com que driver, limite e escala o jogo está abrindo. Na primeira vez de um jogo aparece o aviso de que ela demora mais.',
    where: 'Jogar, na biblioteca ou na ficha.',
    c: 'Igual; B volta para a biblioteca.',
    code: ['ui/ingame/GameLoadingScreen.kt', 'ui/ingame/BootStatusLabel.kt'],
    prints: ['carregamento'],
  },
  launchfail: {
    what: 'Quando o jogo não abre: o motivo numa frase, as últimas linhas do log e o próximo passo para aquele motivo (tentar com o driver do sistema, abrir os saves, tentar de novo). O seletor Motivo, na barra do simulador, troca o exemplo.',
    where: 'Aparece sozinha quando a abertura de um jogo falha.',
    c: 'Igual, com A no botão principal e B para voltar.',
    code: ['EmulatorHostActivity.kt', 'ui/ingame/GameLoadingScreen.kt'],
    prints: ['falha-ao-abrir'],
  },
  ingame: {
    what: 'O menu em jogo: um painel sobre o jogo com cinco categorias (Imagem, Desempenho, HUD, Controles e Sessão), cada linha com o valor e a mudança ali mesmo. O que muda fica guardado para o jogo, com Desfazer e Usar em todos os jogos.',
    where: 'Com o jogo aberto: deslize a partir da borda esquerda, toque em Voltar ou aperte o Guia do controle.',
    c: 'Painel maior; ↑ ↓ entre as linhas, ◀ ▶ muda o valor, A aciona, LB/RB trocam de categoria, B fecha.',
    code: ['ui/ingame/InGameMenu.kt', 'ui/ingame/InGameMenuState.kt', 'settings/InGameChanges.kt', 'EmulatorHostActivity.kt'],
    prints: ['menu-imagem', 'menu-sessao'],
  },
  hud: {
    what: 'O HUD de desempenho sobre o jogo: só FPS, métricas ou o painel completo (ritmo, trabalho, calor e ajustes em vigor), numa caixa vertical ou numa barra horizontal, e o aviso de calor. Formato, detalhe e aviso mudam pelos seletores da barra do simulador; no app, pelo menu em jogo → HUD.',
    where: 'Menu em jogo → HUD → Mostrar o HUD.',
    c: 'Igual (o HUD não muda com o modo).',
    code: ['FpsOverlay.kt', 'core/HudPlacement.kt', 'core/HudMetric.kt', 'ui/ingame/PerformancePanelText.kt'],
    prints: ['hud'],
  },
  controls: {
    what: 'A área Controles: quem joga como P1 a P4, as opções do toque e os layouts salvos, cada controle físico com a própria vibração, vibração e movimento, os telefones como controle e as quatro ferramentas.',
    where: 'Trilho → Controles.',
    c: 'Mesmas seções no menu vertical.',
    code: ['ui/controls/ControlsScreen.kt', 'ui/controls/TouchOptions.kt'],
    prints: ['controles', 'controles-moderno'],
  },
  keymap: {
    what: 'O mapeamento das teclas: o controle desenhado e a lista dos 16 botões com a tecla de cada um. A captura muda um botão num toque; uma tecla já usada troca de lugar.',
    where: 'Controles → Mapeamento.',
    c: 'A escolhe o botão, Y limpa, X troca A/B e X/Y.',
    code: ['ui/keymap/KeymapScreen.kt', 'ui/keymap/KeymapViewModel.kt', 'data/GameButtons.kt'],
    prints: ['mapeamento'],
  },
  touchedit: {
    what: 'O editor dos controles de toque: arrastar com alinhamento à grade, o painel do controle escolhido (tamanho, zona morta, mostrar ou esconder), desfazer, os layouts salvos e as opções gerais.',
    where: 'Controles → Editor de toque, ou menu em jogo → Controles → Editar o layout.',
    c: 'LB/RB escolhem o controle, o direcional move uma casa, A abre o painel.',
    code: ['gamepad/GamepadEditorScreen.kt', 'gamepad/GamepadOverlay.kt'],
    prints: ['editor-toque'],
  },
  padtest: {
    what: 'O teste de controles: o controle desenhado acende o que é apertado, com os analógicos e a zona morta do núcleo, os gatilhos, o giroscópio e a vibração. Nada vai para um jogo.',
    where: 'Controles → Testar controles, ou Configurações → Diagnóstico e testes.',
    c: 'Segure B por um segundo para sair.',
    code: ['ui/controllertest/ControllerTestScreen.kt'],
    prints: ['testar-controles'],
  },
  phonepad: {
    what: 'O celular como controle, no telefone que vai jogar como P2 a P4: endereço do jogo, código de 6 dígitos, nome mostrado e vibração. O código 482913 conecta no exemplo.',
    where: 'Controles → Celular como controle. No telefone do jogo: menu em jogo → Controles → Telefones como controle.',
    c: 'Igual.',
    code: ['ui/companion/PhoneControllerScreen.kt', 'companion/CompanionHost.kt'],
    prints: ['celular-controle'],
  },
  profiles: {
    what: 'Os perfis: cartões com avatar, gamertag, idioma e região, quem é o P1, quem joga como P2 a P4, perguntar quem joga antes de cada jogo e a lixeira de perfis.',
    where: 'Trilho → Perfis.',
    c: 'Avatares grandes em linha; A abre as opções do perfil.',
    code: ['ui/profile/ProfilesScreen.kt', 'ui/library/PlayAsDialog.kt'],
    prints: ['perfis'],
  },
  saves: {
    what: 'Os saves de um jogo por perfil (gamertag, tamanho e último save), exportar e importar com revisão antes de restaurar e a pasta de sincronização com os backups dela.',
    where: 'Ficha do jogo → Saves e dados → Abrir saves.',
    c: 'Mesmas seções no menu vertical.',
    code: ['ui/saves/SaveManagerScreen.kt', 'saves/BackupSync.kt'],
    prints: ['saves'],
  },
  content: {
    what: 'O conteúdo instalado de todos os jogos (DLC e title updates, com tamanhos), a lixeira com a cota e a instalação dos pacotes achados em Downloads e nas pastas de conteúdo.',
    where: 'Trilho → Conteúdo; pela ficha, só o daquele jogo.',
    c: 'Mesmas seções no menu vertical.',
    code: ['ui/content/ContentScreen.kt', 'ui/content/InstallContentViewModel.kt', 'ui/content/ContentCatalog.kt'],
    prints: ['conteudo', 'instalar-conteudo'],
  },
  diagnostics: {
    what: 'As sessões guardadas com como cada uma terminou e o motivo, o resumo da sessão e, antes de compartilhar, o que vai no arquivo e o que sai.',
    where: 'Configurações → Diagnóstico e testes → Diagnóstico; ficha do jogo → Saves e dados.',
    c: 'Mesmas seções no menu vertical.',
    code: ['ui/diagnostics/DiagnosticsScreen.kt', 'core/SessionLogs.kt', 'core/SanitizedSessionExport.kt'],
    prints: ['diagnostico', 'diagnostico-resumo'],
  },
  compare: {
    what: 'Comparar execuções: execuções de um jogo marcadas A ou B, o veredito recalculado na hora com os avisos (ordem, aquecimento, execução curta, mais de uma mudança) e a diferença por par. Os números deste exemplo são de um jogo fictício.',
    where: 'Configurações → Diagnóstico e testes → Comparar execuções.',
    c: 'Mesmas seções no menu vertical.',
    code: ['ui/benchmark/BenchmarkScreen.kt', 'sessions/Benchmark.kt'],
    prints: ['comparar'],
  },
  firstrun: {
    what: 'O assistente da primeira abertura, em cinco passos com Pular e Voltar: este telefone (GPU Vulkan, ARM de 64 bits, Android, pasta), seus jogos, idioma e região dos jogos, o perfil e como usar.',
    where: 'Abre sozinho na primeira vez; depois, menu ⋮ da biblioteca → Assistente de configuração ou Sobre.',
    c: 'Cada passo começa no botão principal.',
    code: ['ui/library/FirstRunAssistant.kt', 'ui/library/FirstRun.kt'],
    prints: ['primeira-abertura', 'primeira-abertura-jogos'],
  },
  folders: {
    what: 'As pastas de jogos: quantos jogos cada uma tem, a que recebe as instalações, as indisponíveis agora, adicionar, procurar de novo e remover com Desfazer (os arquivos nunca são tocados).',
    where: 'Menu ⋮ da biblioteca → Pastas de jogos (Android 11 ou mais novo).',
    c: 'Mesmas ações em lista.',
    code: ['ui/library/GameFoldersScreen.kt', 'data/LibraryRoots.kt'],
    prints: ['pastas'],
  },
  browse: {
    what: 'O navegador de pastas: armazenamento interno e cartões, o caminho em passos clicáveis, quantos jogos há em cada pasta antes de escolher e Nova pasta. Também escolhe um arquivo (um pacote em Conteúdo ou o jogo que mudou de lugar).',
    where: 'Ao adicionar uma pasta de jogos, escolher um pacote ou procurar um jogo que mudou de lugar.',
    c: 'Igual.',
    code: ['ui/library/FolderBrowserScreen.kt', 'data/FolderGames.kt'],
    prints: ['navegador'],
  },
  missing: {
    what: 'Os jogos que saíram da biblioteca: capa guardada, motivo, tempo jogado e o caminho de antes; “Onde ele está agora?” abre o navegador perto do caminho antigo.',
    where: 'Menu ⋮ da biblioteca → Jogos que saíram da biblioteca (só aparece quando há).',
    c: 'Igual.',
    code: ['ui/library/MissingGamesScreen.kt', 'data/TitleRegistry.kt'],
    prints: ['jogos-que-sairam'],
  },
  novulkan: {
    what: 'A tela de um aparelho sem GPU Vulkan: o porquê, as verificações, Sair e copiar os dados do aparelho.',
    where: 'Aparece no lugar da biblioteca quando o aparelho não tem Vulkan.',
    c: 'Igual.',
    code: ['ui/library/NoVulkanScreen.kt', 'ui/library/FirstRun.kt'],
    prints: ['sem-vulkan'],
  },
  update: {
    what: 'As atualizações do app: versão instalada, canal, última procura e o cartão da atualização com o resumo e as etapas baixar, conferir o SHA-256 e instalar. Aqui a build anterior faz o papel da instalada, e a oferecida é a estável publicada, com título, tamanho, SHA-256 e resumo da própria release. O seletor Estado, na barra do simulador, troca o exemplo.',
    where: 'Configurações → Atualizações; menu ⋮ da biblioteca → Procurar atualizações; Sobre.',
    c: 'Igual.',
    code: ['updater/UpdateScreen.kt', 'updater/updater.kt', 'updater/ReleaseFeed.kt'],
    prints: ['atualizador'],
  },
  about: {
    what: 'Sobre: a versão, o aparelho numa tabela com copiar tudo, atalhos para atualizações, diagnóstico e o assistente, créditos e licenças.',
    where: 'Configurações → Sobre; menu Start com controle.',
    c: 'Igual.',
    code: ['ui/about/AboutScreen.kt', 'ui/about/DeviceInfo.kt'],
    prints: ['sobre'],
  },
  msgbox: {
    what: 'Quando o jogo faz uma pergunta: um painel que diz qual jogo pergunta, o texto (que rola quando é longo) e as opções em linhas inteiras. O jogo fica parado até a resposta.',
    where: 'Aparece sozinho durante o jogo.',
    c: 'Dicas de botão embaixo; B avisa que o jogo espera.',
    code: ['ui/messagebox/GuestMessageBoxPanel.kt', 'ui/panel/GuestPanelFrame.kt'],
    prints: ['mensagem'],
  },
  keyboard: {
    what: 'Quando o jogo pede um texto: o pedido, o campo com o limite contado como o jogo conta e a grade de letras e símbolos com as teclas de comando em português.',
    where: 'Aparece sozinho durante o jogo (gamertags, nomes de save).',
    c: 'Atalhos do Xbox 360 à vista: A digita, X apaga, Y espaço, LB/RB cursor, L3 Shift, R3 símbolos, ≡ pronto.',
    code: ['ui/keyboard/GuestKeyboardPanel.kt', 'ui/keyboard/KeyboardGrid.kt'],
    prints: ['teclado'],
  },
  discswap: {
    what: 'Quando o jogo pede outro disco: o disco pedido em destaque e já escolhido, os discos achados com o arquivo de cada um, o de antes marcado e Cancelar por último.',
    where: 'Aparece sozinho em jogos de vários discos.',
    c: 'Dicas de botão embaixo.',
    code: ['ui/disc/DiscSwapPanel.kt'],
    prints: ['troca-de-disco'],
  },
};
