/**
 ******************************************************************************
 * Snapdragon Game Super Resolution 1 guest output effect (XenDroid port).    *
 * Copyright (c) 2025, Qualcomm Innovation Center, Inc. All rights reserved.  *
 * SPDX-License-Identifier: BSD-3-Clause - see third_party/sgsr/LICENSE.      *
 ******************************************************************************
 */

#include "guest_output_sgsr.xesli"
