[APU]
apu = 'aaudio'
apu_aaudio_buffer_bursts = 4
apu_aaudio_dynamic_rate = true
apu_aaudio_log_stats = false
apu_max_queued_frames = 8
apu_performance_hint = true
apu_pump_topup = true
enable_xmp = true
ffmpeg_verbose = false
use_dedicated_xma_thread = true
volume = 100
xma_decoder = 'new'

[CPU]
a64_native_reserved_ops = true
a64_park_spin_backoff = true
a64_perf_map = true
break_condition_gpr = -1
break_condition_op = 'eq'
break_condition_truncate = true
break_condition_value = 0
break_on_debugbreak = true
break_on_instruction = 0
break_on_start = false
break_on_unimplemented_instructions = true
clock_no_scaling = false
clock_source_raw = false
collapse_ctr_spin_loops = true
collapse_memory_delay_spins = true
context_promote_vec128 = true
cpu = 'any'
cpu_trace_mask = 0
disable_context_promotion = false
disable_instruction_infocache = false
disable_prefetch_and_cachecontrol = true
disassemble_functions = false
dump_functions_at = ''
dump_translated_hir_functions = false
emit_inline_mmio_checks = false
emit_mmio_aware_stores_for_recorded_exception_addresses = true
enable_early_precompilation = false
full_optimization_even_with_debug = false
ignore_trap_instructions = true
inline_gprlr_saverest = true
inline_gprlr_saverest_parts = 3
inline_leaf_calls = true
inline_leaf_max_instructions = 16
inline_mmio_access = true
load_module_map = ''
log_delay_collapse_rejects = false
log_guest_call_fields = ''
log_guest_calls_at = ''
log_guest_calls_limit = 1000
log_memory_poll_park = false
log_safepoint_pc = false
log_spin_loop_rejects = false
log_spin_wait_histogram = false
no_reserved_ops = false
park_memory_poll_loops = true
permit_float_constant_evaluation = false
pvr = 7407360
record_mmio_access_exceptions = true
store_all_context_values = false
trace_function_coverage = false
trace_function_data = false
trace_function_data_path = ''
trace_function_references = false
trace_functions = false
validate_hir = false
wfe_precise_sleep = false
wfe_yield = true
writable_code_segments = false

[Config]
defaults_date = 2026080113

[Console]
allow_nui_initialization = false
audio_flag = 65537
internal_display_resolution = 8
use_50Hz_mode = false
user_country = 103
user_language = 1
video_standard = 1
widescreen = true
xmp_default_volume = 70

[Content]
license_mask = 0

[Display]
fullscreen = false
host_present_from_non_ui_thread = true
postprocess_antialiasing = ''
postprocess_dither = true
postprocess_ffx_cas_additional_sharpness = 0
postprocess_ffx_fsr_max_upsampling_passes = 4
postprocess_ffx_fsr_sharpness_reduction = 0.20000000298023224
postprocess_scaling_and_sharpening = ''
present_letterbox = true
present_render_pass_clear = true
present_safe_area_x = 90
present_safe_area_y = 90
show_debug_overlay = false

[GPU]
accurate_resolve_number_formats = false
anisotropic_override = -1
async_shader_compilation = true
async_shader_skip_draws = true
async_shader_vs_interpreter = true
async_shader_vs_interpreter_debug_color = false
clear_memory_page_state = false
depth_bias_shader_offset = false
depth_float24_convert_in_pixel_shader = false
depth_float24_round = false
depth_transfer_not_equal_test = true
disassemble_pm4 = false
draw_resolution_scale_threshold = 0
draw_resolution_scale_x = 1
draw_resolution_scale_y = 1
draw_resolution_scaled_texture_offsets = true
dump_shaders = ''
execute_unclipped_draw_vs_on_cpu = true
execute_unclipped_draw_vs_on_cpu_for_psi_render_backend = true
execute_unclipped_draw_vs_on_cpu_with_scissor = false
force_convert_line_loops_to_strips = false
force_convert_quad_lists_to_triangle_lists = false
force_convert_triangle_fans_to_lists = false
force_convert_triangle_strips_to_lists = false
framerate_limit = 0
gamma_decode_pwl_resolve = true
gamma_render_target_as_unorm16 = true
gpu = 'vulkan'
gpu_3d_to_2d_texture = true
gpu_allow_invalid_fetch_constants = true
gpu_allow_invalid_upload_range = false
gpu_debug_markers = false
gpu_stall_spin_iterations = 32
guest_display_refresh_cap = true
half_pixel_offset = true
ignore_32bit_vertex_index_support = false
log_gpu_frame_time_breakdown = false
log_guest_driven_gpu_register_written_values = false
log_resolve_details = false
log_ringbuffer_kickoff_initiator_bts = false
memexport_await_fences = false
memexport_enable = false
mrt_edram_used_range_clamp_to_min = true
native_2x_msaa = true
native_stencil_value_output = true
no_discard_stencil_in_transfer_pipelines = false
non_seamless_cube_map = true
occlusion_query = 'fast'
occlusion_query_fake_lower_threshold = 80
occlusion_query_fake_upper_threshold = 100
occlusion_query_log = false
occlusion_query_querybatch_range = 0
occlusion_query_saturation = 1
pipeline_storage_precreate = true
precise_interpolation = true
primitive_processor_cache_min_indices = 4096
readback_resolve = 'uma'
readback_resolve_half_pixel_offset = false
readback_resolve_sync = true
render_area_dirty_extent = false
render_target_path = 'performance'
resolve_check_number_format = true
resolve_copy_dest_number_packing = false
resolve_resolution_scale_fill_half_pixel_offset = true
rt_cache_ownership_claim_memo = true
shader_profiling = false
shared_memory_zero_copy = true
snorm16_render_target_full_range = true
spirv_disable_rounding_mode_rte = false
spirv_moltenvk_allow_contraction = true
spirv_multiply_zero_test_on_bits = false
spirv_switch_case_jump_fallthrough = false
spirv_version_override = '1.0'
store_shaders = true
submit_on_primary_buffer_end = true
target_trace_file = ''
texture_cache_memory_limit_hard = 768
texture_cache_memory_limit_render_to_texture = 24
texture_cache_memory_limit_soft = 384
texture_cache_memory_limit_soft_lifetime = 30
texture_gradient_exp_bias = false
texture_integer_num_format = false
tiled_shared_memory = true
trace_dump_path = ''
trace_gpu_prefix = 'scratch/gpu/'
trace_gpu_stream = false
use_fuzzy_alpha_epsilon = false
value_convert_7e3_8888_reuse = true
vulkan_mid_frame_submission_draws = 1300

[General]
allow_game_relative_writes = false
allow_plugins = false
apply_patches = true
controller_hotkeys = false
debug = false
disable_doubleclick_fullscreen = false
discord = false
dump_xex = false
guest_crash_is_fatal = true
launch_module = ''
priority_class = 0
recent_titles_entry_amount = 10
time_scalar = 1

[HID]
guide_button = true
hid = 'android'
left_stick_deadzone_percentage = 0
right_stick_deadzone_percentage = 0
show_touch_overlay = true
vibration = true

[Kernel]
allow_avatar_initialization = false
allow_incompatible_title_update = true
apply_title_update = true
auto_reset_event_handoff = false
cl = ''
console_type = -1
default_achievements_backend = 'GPD'
fiber_reentry_longjmp = true
guest_scheduler = true
guest_scheduler_quantum_us = 1000
guest_scheduler_stats = false
ignore_thread_affinities = true
ignore_thread_priorities = true
in_process_title_relaunch = true
kernel_build_version = 1888
kernel_cert_monitor = false
kernel_debug_monitor = false
kernel_display_gamma_power = 2.2222223300000001
kernel_display_gamma_type = 2
kernel_pix = false
network_enabled = true
precise_guest_delays = true
staging_mode = false

[Logging]
flush_log = true
log_file = ''
log_high_frequency_kernel_calls = false
log_level = 2
log_mask = 0
log_sessions_keep = 4
log_string_format_kernel_calls = false
log_to_debugprint = false
log_to_stdout = true

[Memory]
ignore_offset_for_ranged_allocations = false
mmap_address_high = 8
protect_on_release = false
protect_zero = true
scribble_heap = false
scribble_heap_value = 0
writable_executable_memory = true

[Profiles]
logged_profile_slot_0_xuid = 'E030000070779EA0'
logged_profile_slot_1_xuid = ''
logged_profile_slot_2_xuid = ''
logged_profile_slot_3_xuid = ''

[Storage]
cache_root = ''
content_root = ''
force_mount_devkit = false
mount_cache = false
mount_memory_unit = false
mount_scratch = false
storage_root = ''

[UI]
achievement_notification_position_by_game = false
achievement_sound_path = ''
android_disc_swap = true
android_message_box = true
android_soft_keyboard = true
custom_font_path = ''
font_size = 13
headless = true
profiler_dpi_scaling = false
show_achievement_notification = true
show_profiler = false
storage_selection_dialog = false

[Video]
avpack = 8
enable_3d_mode = false
interlaced = false
internal_display_resolution_x = 1280
internal_display_resolution_y = 720

[Vulkan]
adrenotools_force_max_clocks = true
fd_dev_features = ''
ir3_debug = ''
turnip_debug = 'sysmem'
turnip_perf_sampler = ''
turnip_perf_sampler_file = ''
turnip_perf_sampler_period_ms = 100
vulkan_allow_present_mode_fifo_relaxed = true
vulkan_allow_present_mode_immediate = true
vulkan_allow_present_mode_mailbox = true
vulkan_allow_reverse_z = true
vulkan_async_skip_draws = true
vulkan_avoid_geometry_shaders = true
vulkan_cache_sampler_parameters = true
vulkan_cache_texture_descriptors = true
vulkan_clamp_storage_buffer_range = 0
vulkan_deferred_cmd_size_cursor = true
vulkan_depth_unorm24 = true
vulkan_device = -1
vulkan_direct_host_resolve = true
vulkan_dynamic_constant_buffers = false
vulkan_dynamic_pipeline_state = true
vulkan_dynamic_rendering = true
vulkan_fast_register_ranges = true
vulkan_fast_sampler_filterability = true
vulkan_hoist_shmem_uploads = true
vulkan_in_pass_resolve = false
vulkan_in_pass_resolve_debug_dump = false
vulkan_in_pass_resolve_debug_exp_bias = 0
vulkan_in_pass_resolve_debug_read_usage = false
vulkan_in_pass_resolve_debug_reject = 0
vulkan_in_pass_transfers = true
vulkan_lib_path = '/data/user/0/xendroid.compose.fork.opt/compose/driver/Turnip_Gen8_V36/libvulkan_freedreno.so'
vulkan_log_debug_messages = false
vulkan_normalize_dontcare_keys = true
vulkan_pipeline_creation_threads = 4
vulkan_placeholder_pipelines = false
vulkan_rebar = false
vulkan_renderdoc_capture = false
vulkan_resolve_to_texture = true
vulkan_resolve_to_texture_promote = true
vulkan_resolve_to_texture_serve = true
vulkan_shared_memory_host_visible = true
vulkan_skip_redundant_fetch_constant_writes = true
vulkan_sparse_shared_memory = true
vulkan_texture_descriptor_reuse_edge = false
vulkan_validation = 0

[a64]
a64_enable_host_guest_stack_synchronization = true
a64_extension_mask = -1
a64_max_stackpoints = 65536
a64_vmx_nan_fixup = true