// Autogenerated by xenia-build.py.
#ifndef GENERATED_VERSION_H_
#define GENERATED_VERSION_H_
#define XE_BUILD_BRANCH "canary_experimental"
#define XE_BUILD_COMMIT "dc561e4df578c903087f9bdf56ff61d9ef9f2a93"
#define XE_BUILD_COMMIT_SHORT "dc561e4df"
#define XE_BUILD_DATE __DATE__
#endif  // GENERATED_VERSION_H_
